version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
      - "8208:80"        # Único ponto de entrada público exposto no host
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "8080"           # Apenas acessível internamente pelo Nginx / rede interna
    depends_on:
      - auth-service
    environment:
      - TMDB_API_KEY
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - JWT_SECRET
      - AUTH_SERVICE_URL=http://auth-service:8081
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    expose:
      - "8081"           # Exclusivo rede interna Docker — NUNCA exposto ao host
    environment:
      - MAILTRAP_API_TOKEN
      - MAILTRAP_INBOX_ID
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - JWT_SECRET
      - FRONTEND_URL=https://gabriel-assis-isw055.lapps.studio
      - ASPNETCORE_URLS=http://+:8081
    networks:
      - app-network
    restart: unless-stopped
